services:

  postgres:
    image: postgres:15-alpine
    container_name: devguard_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ibrohim0811
      POSTGRES_DB: devguard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d devguard"]
      interval: 3s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: devguard_redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    container_name: devguard_web
    working_dir: /app
    command: sh -c "alembic -c /app/alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  worker:
    build: .
    container_name: devguard_worker
    working_dir: /app
    command: celery -A utils.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  bot:
    build: .
    container_name: devguard_bot
    working_dir: /app
    command: python bot/main.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      web:
        condition: service_started
      redis:
        condition: service_started
    restart: always

  nginx:
    image: nginx:alpine
    container_name: devguard_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    restart: always

volumes:
  postgres_data: