version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: devguard_redis
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    container_name: devguard_web
    working_dir: /app
    # Alembic-ga -c orqali fayl yo'lini anq ko'rsatamiz:
    command: sh -c "alembic -c /app/alembic.ini upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  worker:
    build: .
    container_name: devguard_worker
    working_dir: /app
    command: celery -A utils.celery_app worker --loglevel=info --concurrency=2
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  bot:
    build: .
    container_name: devguard_bot
    working_dir: /app
    command: python bot/main.py
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - web
      - redis
    restart: always

  nginx:
    image: nginx:alpine
    container_name: devguard_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./staticfiles:/app/staticfiles:ro
      - ./media:/app/media:ro
    depends_on:
      - web
    restart: always