"""add age column to users

Revision ID: 48f0a1318e4d
Revises: 
Create Date: 2026-08-14 01:13:17.975313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48f0a1318e4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('phone_number', sa.String(length=13), nullable=True),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=400), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('web_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_subdomain', sa.Boolean(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('verification_token', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain'),
    sa.UniqueConstraint('slug'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_table('scan_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webapp_id', sa.Integer(), nullable=False),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('scan_type', sa.Enum('DDOS', 'FULL_SCAN', name='scantype'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['webapp_id'], ['web_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_histories_task_id'), 'scan_histories', ['task_id'], unique=True)
    op.create_table('transaction_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webapp_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(length=300), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'DECLINED', 'TIMEOUT', name='transactionstatus'), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['webapp_id'], ['web_applications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_histories')
    op.drop_index(op.f('ix_scan_histories_task_id'), table_name='scan_histories')
    op.drop_table('scan_histories')
    op.drop_table('web_applications')
    op.drop_table('users')
    # ### end Alembic commands ###
